Added a ton of stuff... too much to list here :/

diff --git a/common/bashrc.d/40-functions b/common/bashrc.d/40-functions
--- a/common/bashrc.d/40-functions
+++ b/common/bashrc.d/40-functions
@@ -5,14 +5,43 @@
 source $HOME/.bashrc.d/10-colors
 
 cmds () {
-    cat $HOME/.bashrc.d/*functions | grep "()" | grep -v "^_" | egrep -v "^[A-Z_]*=" | grep -v "cmds" | grep -v "^\s*#" | sed "s/\s\?()//" | sed 's/ { \# /\t/' | awk '{ printf "%-16s %s\n", $1, substr($0,index($0,$2)) }'
+    cat $HOME/.bashrc.d/*functions | grep "()" | grep -v "^_" | egrep -v "^[A-Z_]*=" | grep -v "cmds" | grep -v "^\s*#" | sed "s/\s\?()//" | sed 's/ { \# /\t/' | awk '{ printf "%-16s %s\n", $1, substr($0,index($0,$2)) }' | sort
+}
+
+now() { # seconds since epoch UTC
+	date -u +%s
+}
+
+myip() { # show external IP
+	curl checkip.dyndns.org
+}
+
+dns() { # show dns settings
+	nmcli dev list iface eth0
+}
+
+title () { # set the terminal title
+    [[ "${TERM}" != 'linux' ]] &&
+        printf "\033]0;%s\007\n" "$@"
 }
 
 ts() { # timestamp
 	date +"%Y%m%d.%H%M"
 }
 
-hr() { # echoes a horizontal rule
+return-code() { # echoes the return code of the last command
+	echo $?
+}
+
+fullpath() { # echoes the full path of a file E.g. fullpath <file> [depth]
+	local depth=1
+	if [ -n "$2" ]; then
+		let depth=$2
+	fi
+	find "$(pwd)" -maxdepth "$depth" -iname $1
+}
+
+hr() { # echoes a horizontal rule E.g. hr [number]
 	local times=1
         if [ -n "$1" ]; then
 		let times=$1
@@ -22,6 +51,14 @@ hr() { # echoes a horizontal rule
 	do
 		printf "${Yellow}%$(tput cols)s${Normal}\n"|tr ' ' '='
 	done
+}
+
+ports() { # echoes the listen ports
+	netstat -tln | sort
+}
+
+ram() { # prints human-readable RAM usage for every process
+	ps -eo size,pid,user,command --sort -size | awk '{ hr=$1/1024 ; printf("%13.2f Mb ",hr) } { for ( x=4 ; x<=NF ; x++ ) { printf("%s ",$x) } print "" }'
 }
 
 cb() { # cd up to a certain directory name
@@ -42,6 +79,10 @@ groovy_files() { # find all groovy files from the current directory
 
 java_files() { # find all java files from the current directory
     _find_file_w_extension "*.java"
+}
+
+js_files() { # find all java files from the current directory
+    _find_file_w_extension "*.js"
 }
 
 _grepit() {
@@ -74,6 +115,10 @@ fsig() { # find a given string in scala files, ignoring tests
         hr 2
 }
 
+fsf() { # finds a scala file with the given string in its name (case-insensitive)
+	scala_files | grep -i "$@"
+}
+
 fsc() { # finds a scala class, object, or trait (case-insensitive)
     scala_files | xargs ack-grep -il --color-match=yellow  --match "(class|object|trait) [a-zA-Z]*$1"
 }
@@ -94,10 +139,6 @@ fai() { # finds a given string in any file (case-insensitive)
 	find . -type f | _grepit -i "$@"
 }
 
-fsf() { # finds a scala file with the given string in its name (case-insensitive)
-	scala_files | grep -i "$@"
-}
-
 fgr() { # finds a given string in groovy files
 	_find_whatev groovy_files "$@"
 }
@@ -112,6 +153,18 @@ fj() { # finds a given string in java files
 
 fji() { # finds a given string in java files (case-insensitive)
 	_find_whatev_i java_files "$@"
+}
+
+fjs() { # finds a given string in js files.
+	hr 2
+	_find_whatev js_files "$@"
+	hr 2
+}
+
+fjsi() { # finds a given string in js files (case-insensitive)
+	hr 2
+	_find_whatev_i js_files "$@"
+	hr 2
 }
 
 fjar() { # find jar in ivy cache (case-insensitive)
@@ -132,6 +185,10 @@ manifest() { # prints the manifest of the given jar
 
 backup-eclipse() { # zips all .classpath and .project files generated by eclipse
 	zip -R eclipse.env.backup-`date +%Y%m%d`.zip .classpath .project
+}
+
+eclipse-fix-classpath() { # changes bin to .eclipse
+	find . -name \.classpath -exec sed -i -e 's/kind=\"output\" path=\"bin\"/kind=\"output\" path=\".eclipse\"/g' {} \;
 }
 
 killgrep() { # kills all processes containing the string, killgrep <name> <signal>, E.g. killgrep java -1
